### ISSUE TITLE
Still in use?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zc.zope3recipes#10]
Is this package still actively used or can it be archived?
Currently the tests for Windows are broken (see #9) – We could remove Windows support as the README says it's only alpha quality.

Cc-ing contributors:

@mgedmin @freddrake @zvezdan @projekt01

P.S.: I personally do not use it.

**Comment by mgedmin** [comment]
Unfortunately I do use it.

+1 for dropping Windows support.

**Comment by agroszer** [comment]
not in use here

**Comment by icemac** [comment]
@mgedmin wrote:
> +1 for dropping Windows support.

Do you think you can come up with a pull request to do so? (Maybe even based on #9.)

**Comment by icemac** [comment]
I just released https://pypi.org/project/zc.zope3recipes/1.0/ without official Windows support.
